# Generated by Django 5.1.5 on 2025-02-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='counter',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество просмотров'),
        ),
    ]
