# Generated by Django 5.1.5 on 2025-02-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='counter',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
